[tool.poetry]
name = "arc-cli"
version = "3.2.0"
description = "A Regular CLI"
authors = ["Sean Collings <seanrcollings@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/seanrcollings/arc"
documentation = "https://github.com/seanrcollings/arc/wiki"
keywords = ["CLI", "extendable", "easy", "arc"]
classifiers= [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
]
packages=[{ include = "arc" }]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
mypy = "^0.800"
pylint = "^2.7.0"
pytest = "^6.2.4"
pdoc = "^7.1.1"


[tool.poetry.scripts]
arc = "arc.application:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
